### ISSUE TITLE
Lists, Arrays

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#104]
Part of #102.
Found that returning arrays and lists can be created with `FromGlibPtrContainer`.
But not sure what use for converting parameters. `IterToGlibPtr`?

**Comment by gkoz** [comment]
I should merge the changes to the `translate` traits into `object_reform` soon... I decided to abandon iterators support for the time being and simply implement `ToGlibPtr` for slices. [Example use](https://github.com/rust-gnome/gtk/blob/master/src/widgets/about_dialog.rs#L138-144):
```rust
    pub fn set_authors(&self, authors: &[&str]) {
        unsafe {
            ffi::gtk_about_dialog_set_authors(
                GTK_ABOUT_DIALOG(self.unwrap_widget()), // this is on the master branch
                authors.to_glib_none().0);
        }
    }
```

**Comment by EPashkin** [comment]
Thanks.
