### ISSUE TITLE
Support optional outparam return types

### ISSUE THREAD

**Issue by gkoz** [gkoz/gir#119]
Some functions return `bool` in addition to outparams with the understanding that returning `FALSE` means the outparams haven't been initialized, this should translate to `None`.

Example: `gtk_widget_translate_coordinates`.

**Comment by EPashkin** [comment]
Full list of GTK functions can be received by XPath `//method[return-value[type[@name="gboolean"]] and parameters/parameter[@direction="out"]]`
Ex. `gtk_container_get_focus_chain`

**Comment by gkoz** [comment]
Nice idea, thanks!

**Comment by gkoz** [comment]
All of the command line tools I've tried fail to do anything useful even with just `//method`. Looks like my XML/XPath skills have degraded too much :/

**Comment by gkoz** [comment]
Looks like there're 67 functions of this kind in Gtk, 21 in Gdk. Most seem to fit the rule.
