### ISSUE TITLE
Return Result for errors

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#130]
For throwable function return value must return `Result` (see discussion beginning at https://github.com/gkoz/gir/issues/117#issuecomment-143070962).

2 types of throwable functions:
1) without other outs that will returns `Result<(), glib::Error>`
1.1) Examples of FFI function return guint:
gtk_builder_add_objects_from_string
1.2) Examples of FFI function return gboolean:
gtk_css_provider_load_from_path,
gtk_file_chooser_add_shortcut_folder,
gtk_file_chooser_set_current_folder_file,
gtk_page_setup_load_file,
gtk_print_settings_to_file
1.3) Examples of FFI functions return something usable
gtk_icon_info_load_icon,
gtk_recent_info_create_app_info,
gtk_recent_manager_lookup_item
2) with other outs that will returns tuple(or single value) instead () on good case
Examples:
gtk_builder_value_from_string,
gtk_icon_info_load_symbolic

~~Blocked by #103~~

**Comment by gkoz** [comment]
Additionally, if a throwing function returns `Boolean`, it can just be ignored making it `Result<(), glib::Error>`.

A list of throwing functions, return types and annotations: https://gist.github.com/gkoz/17f2ad8a05447b235b27

**Comment by EPashkin** [comment]
You right about return value.
Thanks for list.

**Comment by gkoz** [comment]
`Error` has conversions impls now, solving this will bring us pretty close to complete coverage of existing `gtk` API.

**Comment by EPashkin** [comment]
Good, I try do it tomorrow
