### ISSUE TITLE
Config::new error processing

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#134]
Currently `Config::new` returns `Result<Config, ConfigError>`, but contains many `panic!` and even `exit`.
Tried to expand ConfigError cases to parsing options in https://github.com/EPashkin/gir/commits/error_case, but code look ugly as needed internal macros (which can be changed to new trait on Toml) and don't cover `min_cfg_version` and starting `Docopt`.

May be better just make `Config::new` return `Config` and panic on `read_toml` result instead passing it to `main`?

**Comment by EPashkin** [comment]
May be I was wrong about possibility converting macros to trait as it need 2 variables from function scope: `toml`, `config_file`.

**Comment by gkoz** [comment]
Adding a trait with a `lookup_str` method to `Toml` seems like a good idea regardless. `map_err` might be a reasonable band-aid, making conversions explicit. If the error handling keeps being problematic I'd be willing to investigate a version of `try!` that would allow giving additional context. The same problem (without a clear solution) has come up in `rustdoc` BTW, so we're not doing anything particularly wrong here.

**Comment by gkoz** [comment]
To use the existing error types, this doesn't look too bad, although it would be clearer if filename was a path, not a string.

```rust
try!(File::open(filename)
    .and_then(|mut f| f.read_to_string(&mut input))
    .map_err(|e| (e, &filename);
```

```rust
impl<'a> From<(io::Error, &'a str)> for ConfigError { ... }
```
