### ISSUE TITLE
Generate safety assertions

### ISSUE THREAD

**Issue by gkoz** [gkoz/gir#174]
All* non-method functions functions need to have safety assertions introduced in https://github.com/gtk-rs/gtk/pull/189, e.g.

```rust
impl Box {
    pub fn new(orientation: Orientation, spacing: i32) -> Box {
        assert_initialized_main_thread!();
        ...
```

\* if we take an object that has an assertion in its constructor, it can be skipped, but this optimization is not strictly necessary:
```rust
 impl Layout {
    pub fn new(hadjustment: &Adjustment, vadjustment: &Adjustment) -> Layout {
        skip_assert_initialized!();
        ...
```

The whole feature should probably be optional.

**Comment by EPashkin** [comment]
Assertion only for objects "static" functions or some records need it too?
Can be term `non-method functions` replaced with `constructors`?

Is safe to say that all objects has assertion in constructor or it depends on other asserted objects?
Then second part equal check constructors for object parameters.

**Comment by gkoz** [comment]
Whether an object is involved or not, we have to start with the assumption that all functions need the assertions but methods obviously don't. It should be workable to rely on all constructors, including the manually written ones, having the assertion.
