### ISSUE TITLE
Version overrides

### ISSUE THREAD

**Issue by gkoz** [gkoz/gir#180]
`gtk_paper_size_is_ipp` seems to be missing a `version="3.16"` annotation. We might either want to support version overrides or just handle this manually.

**Comment by EPashkin** [comment]
From sources in http://ftp.acc.umu.se/pub/gnome/sources/gtk+/ both ipp functions present from "gtk+-3.15.0".

**Comment by gkoz** [comment]
This is consistent with `version=3.16` because odd versions (e.g. 3.15) are tagged on unstable branches and only even versions are released.

**Comment by EPashkin** [comment]
We can add `version` to `[[object.function]]`. I try it tomorrow.
I don't like idea fix it on generated `gir-files`.

**Comment by gkoz** [comment]
While at it consider also something like `cfg_condition` so we could set `cfg_condition = "unix"` for `gio-unix` objects and functions and it would then translate into `#[cfg(unix)]`.

**Comment by EPashkin** [comment]
Ok. I try do it too.
