### ISSUE TITLE
Extra empty line at the end of struct

### ISSUE THREAD

**Issue by GuillaumeGomez** [gkoz/gir#188]
When generating a `struct`, it ends like this:

```Rust
struct Foo {
    fn a() {}

}
```

I'm working on fixing this.

**Comment by EPashkin** [comment]
Now tree_iter.rs has to many empty lines https://github.com/gtk-rs/gtk/blob/master/src/auto/tree_iter.rs.
Same with widget path (currently not generated in gtk-rs) and https://github.com/gtk-rs/gtk/blob/master/src/auto/tree_path.rs#L50-L74
Seems adding line in function before checking its visibility was not good idea

**Comment by gkoz** [comment]
BTW, I had noticed curious extra empty lines even before that change.

**Comment by GuillaumeGomez** [comment]
@gkoz: From my change? Or even before?

**Comment by gkoz** [comment]
Before any of your changes.
