### ISSUE TITLE
Tests module for function generation

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#20]
IMHO we need a module for testing codegen/function.rs functions `declaration` and `body` for some cases.
I not sure where to place this module: in `function.rs` or in tests directory.
Sample tests:
```rust
#[test]
fn decl_gtk_switch_set_active () {
  assert_eq!(code_func_decl("Gtk.Switch", "set_active"), "fn set_active(&self, is_active: bool)");
}
#[test]
fn body_gtk_switch_set_active () {
  assert_eq!(code_func_body("Gtk.Switch", "set_active"), "unsafe { ffi::gtk_switch_set_active(self.to_glib_none().0, is_active.to_glib()); }");
}
```
`code_func_xxx` is helper functions(macros) that get `Libray`, analyses function and call `codegen::function::xxx`.
It would be better if all tests use same copy of `Library`.

**Comment by gkoz** [comment]
Currently I don't see good unit testing possibilities for the codegen modules as they just serialize the data discovered earlier and seem to have many trivial parameters. It would probably make more sense in the analysis modules.

The code generation as a whole might be better tested by some integration tests (in the `tests` directory), but comparing the generated code to some predefined results seems very limiting. Maybe the test should require the generated code and some example crate that uses it to compile.

**Comment by EPashkin** [comment]
I agree that the option that I ask is closer to integration tests.
Now that's what I need to be sure that I did not break anything while working on the generation parameters.
Then, this test can be replaced by normal.
At the moment I do not know the rusted method of single loading `Library` for multiple tests.

**Comment by gkoz** [comment]
> At the moment I do not know the rusted method of single loading Library for multiple tests.

Are you sure the unit tests require loading big libraries? It seems each test should be testing a limited piece of logic that only needs a number of dummy definitions not the whole Gtk.gir

**Comment by EPashkin** [comment]
It not unit test, it semi-integration (parsing-analyze-codegen).
IMHO it better work on full gir, as it "faster" that think up xmls for all corner cases.
As workaround i can commit generated files in git, then i see changes in old converted files.
But if rules of generation little changed (Ex. add Option), then i need review not small subset of tests, but many converted files

**Comment by gkoz** [comment]
If you're good with literal text comparisons, using `diff` seems reasonable: if there's no difference the test passes, otherwise you immediately see what's wrong, for free.

**Comment by EPashkin** [comment]
I can easily miss a error even in diff :(
Currently i do it this way, but if more files changed, it be more difficult.

**Comment by gkoz** [comment]
That's the problem as I see it: a change in the source code is not necessarily an error, that's why it's more reliable to compile a sample crate against the generated code.

**Comment by EPashkin** [comment]
Yes, it will be one of final integration test, but currently it always fail. We missed uses, function params and body.

**Comment by EPashkin** [comment]
And until then, we better have partial tests, that can be solved one by one.

**Comment by EPashkin** [comment]
Seems it really was unnecessary. Closing.
