### ISSUE TITLE
Generate uses code

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#21]
It is necessary to generate a lines with "use xxx;".
I believe that it is better to add some mutable state to avoid duplication.
Not sure it will be added to `env::Env` via `RefCell` or to separate struct.
Now I see the following sources of necessary types:
- Common to all `glib::translate: *, glib::types, ffi`
- `object::{Object, Upcast}` with `DownCast` when constructors present
- parent types, that will be added in `impl_parents`
- interface types from currently not implemented function `impl_interfaces`
- functions parameters

**Comment by gkoz** [comment]
We could avoid importing most of the types by taking advantage of reexports in the root namespace.
```rust
unsafe impl <Upcast<::Container>> for Bin { }
```

**Comment by EPashkin** [comment]
It works if all usable type will reexported.
If some still needed use (Ex. `c_double`) then task still ever 
more difficul, we need do check on both "sides"

**Comment by gkoz** [comment]
Maybe we do need to cache the lines before writing to the file, this would allow is to gather the list of types that must be imported.

**Comment by EPashkin** [comment]
Yes, i proposed this from beginning. May be I was not clear enough.
I try add uses (with interfaces) tomorrow, as I say in beginning of last PR, I prefer get compilable code sooner.

**Comment by EPashkin** [comment]
Closed with #34
