### ISSUE TITLE
Possible problem in parents upcast generation

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#23]
Some types (`GtkCheckButton`) have children and only constructors (no trait).
So for it's children ('GtkRadioButton') we better skip parent upcast.
We can just add empty trait or go hard way.
- add boolean flah in analyze::object::Info
- add cache for this in env::Env (or state)
- then when processing parents, check cache for its Info (analyze if not found) and skip upcast.

Currently seen only `GtkCheckButton`, so empty trait IMHO will do.

**Comment by EPashkin** [comment]
Forgot to say about `GtkScrollbar`, and some others. Its have only deprecated children and can be correctly processed with analog of https://github.com/EPashkin/gir/tree/deprecation.
The latest use not too suitable for this module `semver` and because of this contains hacks.

**Comment by gkoz** [comment]
Retaining consistency (not skipping over some classes in `Upcast` impls) seems worth having a few empty traits.

As to the classes with deprecated/useless subclasses, the analyzer might have to recompute the `has_children` property taking into account the set of widgets present in the toml. If the children aren't present in the config, it's as if there's no children.

**Comment by EPashkin** [comment]
Agree for counting only "listed" children.
