### ISSUE TITLE
Problem with types from other libs 

### ISSUE THREAD

**Issue by EPashkin** [gkoz/gir#30]
Now types from other libs shows wrong way. As example `gtk_scale_get_layout` uses `Pango.Layout`, but currently shows as 'Layout'.
To temporary fix problem I start branch https://github.com/EPashkin/gir/tree/comment_types_from_other_libs, but faced the problem: library's Class don't know, what namespace it belong.
Can I add ns:u16 to almost all types?
Final solution for this issue must be using `pango::Layout` string as type?

Also, can I delete row
```
library.namespace_mut(INTERNAL_NAMESPACE).name = INTERNAL_NAMESPACE_NAME.into();
```
and it current replacement as unnecessary?

**Comment by gkoz** [comment]
In what circumstances can you have (presumably a reference to) a `Class` and not know which namespace it comes from. You get a `Class` either from a lookup by `TypeId` which has a `ns_id` or by enumerating the classes of a namespace.

**Comment by gkoz** [comment]
> `library.namespace_mut(INTERNAL_NAMESPACE).name = INTERNAL_NAMESPACE_NAME.into();`

This line does seem redundant.

**Comment by EPashkin** [comment]
1) If i do only ignoring, I need `TypeId`(or ns) in `to_type_kind` method. In all current usage I add additional parameter to method and call will looks like this
```
impl TranslateToGlib for library::Parameter { ...
            let kind = library.type_(self.typ).to_type_kind(library, self.typ);
```
In my opinion it is unnecessary duplication that can cause errors, but i can do it.
2a) For normal solution, i need pass TypeId through `to_parameter_rust_type` to `to_rust_type`. IMHO this is too much.
2b) Other way - add to library's Class (and others) field 'rust_name', that will be calculated in beginning. But now Library assumes some of the responsibilities of the generator. And analyzer/codegen still don't have normal way to tell, if type from main library or not (maybe it unnecessary)

**Comment by gkoz** [comment]
Hmm, I wonder if this is because those methods really want to be implemented for `TypeId` not for `Type` or individual variants.

Here's another idea I've just had. If you implement stuff for `(&'a Library, TypeId)` you don't have to drag the library reference around by hand.

**Comment by EPashkin** [comment]
1. If methods will be implemented only for TypeId, then all logic will be in one place, and it may be unreadable, but may be not. I try it.
2. In fact, `library` there is only needed to determine the widgets. If add "Gtk.widget" when creating the library (at constant id), the `library` of the most likely can get rid of. But it create too strong link to Gtk.
I try `(&'a Library, TypeId)` too.
